name: Crawler

on:
  push:
  schedule:
    - cron: '0 15 * * *'

jobs:
  crawl:
    name: W3C documents fetching
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install gem
        run: |
          gem install relaton-cli
      - name: Fetch documents
        run: relaton fetch-data w3c-rdf
      - name: Push data
        run: |
          echo `date` > flag.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/* flag.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m 'update documents' && git push)